name: Experiment

on:
  # Allow users to trigger workflow manually via the GitHub UI
  workflow_dispatch:

jobs:
  checkout-project:
    name: "Checkout Project"

    runs-on: self-hosted

    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          clean: false
          lfs: true
        
      - name: Check out LFS objects
        run: git lfs checkout

  run-experiment:
    needs: [ checkout-project ]
    name: "Run Experiment"

    runs-on: self-hosted
    
    timeout-minutes: 10

    steps:
      - name: Github step summary testing
        run: ./ThirdParty/Experiments/Experiments.exe